server:
  port: 80
  session-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8
  environment: official #环境 是否开发环境 official 正式环境 develop开发环境

management:
  server:
    port: 5601
  health:
    mail:
      enabled: false

spring:
  application:
    name: XHOA
  datasource:
    url: jdbc:mysql://192.168.2.162:3306/xh-oa?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: xhoa
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    schema: classpath:schema.sql
    initialization-mode: always
    name: druid
    #    data: classpath:data.sql
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 # from dual
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

  security:
    basic:
      enabled: false
  #  jpa:
  #    database: mysql
  #    show-sql: true
  #    hibernate:
  #      ddl-auto: update
  messages:
    basename: i18n/messages
    #    cache-seconds: 3600
    encoding: UTF-8
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  mail:
    host: smtp.163.com
    username: ibyefan@163.com
    password: haoshi1996
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8
    protocol: smtp

  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,/druid/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html

  transaction:
    rollback-on-commit-failure: true
    cache:
      type: redis
      cache-names: redisCache
      redis:
        time-to-live: 60s
        use-key-prefix: true
        key-prefix: cacheee
  redis:
    database: 0
    #  host: 127.0.0.1
    host: 192.168.2.162
    port: 6379
    password: 123456
    timeout: 5000
    #    cluster:
    #      #nodes: 127.0.0.1:6379,192.168.211.134:7001,192.168.211.134:7002
    #      maxRedirects: 6
    lettuce:
      pool:
        max-idle: 10
        min-idle: 5
        max-wait:  100000
        max-active: 500
    jedis:
      pool:
        max-idle: 10
        min-idle: 5
        max-wait:  100000
        max-active: 500

#redis:
#  #  host: 127.0.0.1
#  host: 192.168.2.162
#  port: 6379
#  password: 123456
#  pool:
#    max-active: 500
#    max-idle: 10
#    max-wait: 100000
#  timeout: 2000
#  cluster:
#    #    nodes: 127.0.0.1:6379,192.168.211.134:7001,192.168.211.134:7002
#    nodes: 127.0.0.1:6379
#    maxRedirects: 6
#  jedis:
#    pool:
#      max-idle: 10
#      min-idle: 5
#      max-wait:  100000
#      max-active: 500



mybatis:
  type-aliases-package: com.byefan.xhoa.entity,com.byefan.core.entity
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    multiple-result-sets-enabled: true
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
#
####################  mybatis-plus配置  ###################
mybatis-plus:
  typeAliasesPackage: com.byefan.xhoa.entity,com.byefan.core.entity
  mapper-locations: classpath*:mapping/*.xml
  global-config:
    id-type: 1  #1:数据库ID自增   2:用户输入id   3:全局唯一id(IdWorker)   4:全局唯一ID(uuid)
    #    db-column-underline: false
    #    refresh-mapper: true
    #  configuration:
    #    map-underscore-to-camel-case: true
    #    cache-enabled: true #配置的缓存的全局开关
    #    lazyLoadingEnabled: true #延时加载的开关
    #    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    meta-object-handler: com.jinhuatuo.edu.config.mybatis.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #MyBatis

    #  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0




#pagehelper??????
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      byefan:
        xhoa:
          mapper: debug
          controller: debug
          service: debug
    org:
      springframework: warn
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    level: debug
  file: E:\\logs\\xhoa.log
#    max-size: 10MB
#    max-history: 100

flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  #自动部署验证设置:true-开启（默认）、false-关闭
  check-process-definitions: false


swagger:
  basePackage: com.byefan.xhoa.controller
  #
  #消息服务地址
rocketmq:
  namesrvaddr: 127.0.0.1:9876


const:
  appName: 内部智能管理系统
  #  开发环境
  env: develop #official 正式环境 develop开发环境
  #  上传文件保存
  uploadDir: D:\upfiles/xhoa/
  #  上传文件浏览目录
  webDir:  /statics/
  urls: /**, /user/**
  exUrls: /user/login/**,/static/**,/login,/logout,/code,/403,/404,/500,/error,/api/ws/**,/statics/**,/js/**,/css/**,/img/**,/fonts/**,/layui/**,/plugins/**
  staticPages:
    /statics/**: file:D:\upfiles/xhoa/
    /statics/images/**: file:D:\upfiles/xhoa/images


  pageUrls:
    login: login
    reg: reg
    #    /: index
    head: head
    manage-top: manage/top
    403: common/403
    404: common/403
    500: common/500
    system-logger: system/logger
    crm-custom_add: crm/custom_add
    crm-custom_list: crm/custom_list
    crm-company_common: crm/company_common
    crm-company_docking: crm/company_docking
    crm-company_product: crm/company_product
    crm-company_users: crm/company_users
    crm-company_all: crm/company_all
    crm-docking_edit: crm/docking_edit
    crm-product_edit: crm/product_edit
    crm-users_edit: crm/users_edit
    crm-goal-goal_setting: crm/goal/goal_setting
    crm-statistics-cust_statistics: crm/statistics/cust_statistics  #客户统计
    crm-statistics-cust_manager_statistics: crm/statistics/cust_manager_statistics    #客户管理统计
    workbench-workbench: workbench/workbench
    workbench-items_list: workbench/items_list
    workbench-users_list: workbench/users_list
    biz-business_list: biz/business_list     #业务查询
    biz-business_manager: biz/business_list   #业务管理
    biz-business_edit: biz/business_edit
    biz-article_list: biz/article_list     #稿件管理
    biz-statistics-business_manager_statistics: biz/statistics/business_manager_statistics     #业务首页统计
    biz-statistics-business_statistics: biz/statistics/business_statistics     #业务统计
    biz-income_detail: biz/income_detail   #入账详情
#    biz-orders: biz/orders   #订单管理
    mediauser-mediauser_list: mediauser/mediauser_list   #媒介查询
    mediauser-mediauser_edit: mediauser/mediauser_edit   #媒介编辑
    mediauser-statistics-media_user_statistics: mediauser/statistics/media_user_statistics    #媒介统计
    mediauser-statistics-media_user_manager_statistics: mediauser/statistics/media_user_manager_statistics    #媒介首页统计
    mediauser-statistics-supplier_statistics: mediauser/statistics/supplier_statistics     #供应商统计
    media-medias: media/medias              #媒体查询及下单页面
    media-order: media/order              #媒体查询及下单页面
    media-addMedia: media/addMedia          #媒体登记页面
    media-reviewMedia: media/reviewMedia    #媒体审核页面
    media-modifyMedia: media/modifyMedia    #媒体修改页面
    media-manageMedia: media/manageMedia    #媒体管理页面
    media-supplier_edit: media/supplier_edit    #媒体供应商编辑页面
    media-supplier_manage: media/supplier_manage    #媒体供应商管理页面
    media-audit: media/auditMedia           #媒体审核
    media-audits: media/audits           #媒体审核
    system-queryRole: system/queryRole
    system-editRole: system/editRole
    system-viewRole: system/viewRole
    system-queryGroup: system/queryGroup
    system-editGroup: system/editGroup
    system-viewGroup: system/viewGroup
    system-queryResource: system/queryResource
    system-editResource: system/editResource
    system-viewResource: system/viewResource
    system-queryUser: system/queryUser
    system-editUser: system/editUser
    system-viewUser: system/viewUser
    system-editUserSelf: system/editUserSelf
    system-queryDept: system/queryDept
    system-editDept: system/editDept
    system-viewDept: system/viewDept
    system-changePhoto: system/changePhoto
    system-resource: system/resource
    fee-queryIncome: fee/queryIncome
    fee-queryOutgo: fee/queryOutgo
    fee-queryAssign: fee/queryAssign
    fee-queryAccount: fee/queryAccount
    fee-queryBorrow: fee/queryBorrow
    fee-queryCommission: fee/queryCommission
    fee-queryInvoice: fee/queryInvoice
    fee-queryRefund: fee/queryRefund
    fee-queryReimburse: fee/queryReimburse
    fee-queryReimburseD: fee/queryReimburseD
    dsg-cust_statistics: dsg/cust_statistics
    dsg-index: dsg/index
    process-queryTask: process/queryTask

  #自定义配置
  custConfig:
    # 审批流程的网关参数；
    # 退款申请的流程中判断是否需要总经理审批的金额（含）；
    refundMoney: 50000
    # 媒介请款的流程中网络媒介是否需要财务总监审批的金额（含）；
    mediaRefundMoneyNew: 1000
    # 媒介请款的流程中非网络媒介是否需要财务总监审批的金额（含）；
    mediaRefundMoneyOld: 5000
    # 借款申请的流程中是否需要总经理审批的金额（含）；
    borrowMoney: 5000